### ISSUE TITLE
AttributeError: 'BananaEnv' object has no attribute '_seed'

### ISSUE THREAD

**Issue by avikpram** [MartinThoma/banana-gym#2]
I am getting the following error when i call `env = gym.env('Banana-v0')`

`AttributeError: 'BananaEnv' object has no attribute '_seed'`

Full code:
```python
import gym
import gym_banana

def run():
  env = gym.make('Banana-v0')
# run()

if __name__ == '__main__':
  run()
# done
```

Full traceback :
```
Traceback (most recent call last):
  File "example_banana.py", line 16, in <module>
    run()
  File "example_banana.py", line 10, in run
    env = gym.make('Banana-v0')
  File "C:\Python27\lib\site-packages\gym\envs\registration.py", line 163, in make
    return registry.make(id)
  File "C:\Python27\lib\site-packages\gym\envs\registration.py", line 121, in make
    patch_deprecated_methods(env)
  File "C:\Python27\lib\site-packages\gym\envs\registration.py", line 181, in patch_deprecated_methods
    env.seed  = env._seed
AttributeError: 'BananaEnv' object has no attribute '_seed'
```

**Comment by avikpram** [comment]
I found the solution. See : https://github.com/openai/gym/issues/860

**Comment by MartinThoma** [comment]
Thanks for reporting. I fixed it.

**Comment by BarelySentient** [comment]
What does this solution look like? I don't understand what is going on in gym#860...
